#!/usr/bin/env node
/// <reference types="node" />
// 构建 client.js：rolldown（Rust 系 bundler，与 dsh 自身 tsdown 同底层）把
// src/client-entry.ts + lib/transcript.ts 打包为 CJS（react 外部化），再包进
// window.__ModuleLoader__.load({ id, factory }) UMD 外壳（factory(require)
// 收到模块系统的 require，module/exports 由外壳提供）。
// 运行：node build-client.mjs（或 pnpm build:client）。buildClient() 供测试导入。
// 顶部 node reference：oxlint 类型检查对 .mjs 不自动加载 @types/node，需显式
// 声明才能解析 node:path/node:fs/process/import.meta（否则整文件按 error 类型
// 误报 unsafe）。
import path from "node:path";
import { readFileSync, writeFileSync } from "node:fs";
import { rolldown } from "rolldown";
import { canonicalizeRegionPaths } from "@jayyuen66/dsh-plugin-shared/lib/canonicalize-region-paths";

const root = import.meta.dirname;

/**
 * 从 JSON.parse 的 unknown 投影为 Record（非对象 → 空对象兜底），避免 any 索引。
 * @param {unknown} raw
 * @returns {Record<string, unknown>}
 */
function asRecord(raw) {
  if (raw !== null && typeof raw === "object" && !Array.isArray(raw)) {
    return raw;
  }
  return {};
}

// 模块表 id 必须等于包名：dsh 的 client-modules 只扫裸包名条目并按包名建键，
// 写死字符串会在改名/换装法下静默不渲染卡片（与其余包的 build-client 同口径）。
/** @type {unknown} */
const pkgJson = JSON.parse(readFileSync(path.join(root, "package.json"), "utf8"));
const nameKey = "name";
const nameRaw = asRecord(pkgJson)[nameKey];
const pkgName = typeof nameRaw === "string" ? nameRaw : "unknown";

/** 生成 client.js 的完整文本（含 ModuleLoader 外壳）。 */
export async function buildClient() {
  const bundle = await rolldown({
    input: path.join(root, "src", "client-entry.ts"),
    external: ["react"],
    platform: "browser",
    resolve: {
      extensions: [".ts", ".mjs", ".js", ".json"],
    },
  });
  const { output } = await bundle.generate({
    format: "cjs",
  });
  const chunk = output.find((item) => item.type === "chunk");
  if (chunk === undefined) {
    throw new Error("rolldown generate returned no chunk output");
  }
  // 见 shared/lib/canonicalize-region-paths.ts：`//#region` 行的路径由 rolldown 按 process.cwd()
  // 算出 ⇒ 同一份源码两种字节。折 canonical 必须落在返回值之前（test/client-freshness.ts 逐字节
  // 比内存构建与磁盘产物），不能只在 writeFileSync 那一侧做。
  const body = canonicalizeRegionPaths(chunk.code.trimEnd(), root);
  return [
    "// GENERATED by buildClient() in build-client.mjs — edit src/*.ts + lib/transcript.ts, then run `node build-client.mjs`.",
    "window.__ModuleLoader__.load({",
    `  id: '${pkgName}',`,
    "  factory: (require) => {",
    "    var module = { exports: {} };",
    "    var exports = module.exports;",
    body,
    "    return module.exports;",
    "  },",
    "});",
    "",
  ].join("\n");
}

async function main() {
  const out = await buildClient();
  // 同步落盘（架构必需）：脚本顶层 await 前必须让文件写完成（rolldown 在内存
  // 中已完成，这里一次性同步写比 async 更不易出现半写状态；构建脚本非并发路径）。
  writeFileSync(path.join(root, "client.js"), out, "utf8");
  console.info("client.js written:", out.length, "chars");
}

if (process.argv[1] === import.meta.filename) {
  try {
    await main();
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
}
